### PR TITLE
Unity implementation

### PR DESCRIPTION
**Pull request by Pattrigue**

### CODE REVIEW

**Comment by Pattrigue** [comment]
i'm want the die

**Comment by Pattrigue** [comment]
stop

**Comment by Pattrigue** [comment]
finally, inner peace

**Comment by chhoumann** [comment]
> finally, inner peace

a

**Comment by Pattrigue** [comment]
@Ivikhostrup glhf

**Review by Ivikhostrup — APPROVED** [review]
Will have to see how it will do in code generation, but overall seems solidly wired up. The cleanliness in the folder structure is amazing. gj.

**Pull request merged**
